#!/usr/bin/env php
<?php
require(__DIR__ . '/../../../vendor/autoload.php');
require(__DIR__ . '/../../../vendor/yiisoft/yii2/Yii.php');

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

Yii::setAlias('@inblank/team', __DIR__.'/../..');

$config = require(__DIR__ . '/../config/unit.php');
$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);
